// Pi harness parity PR 2 (docs/plans/evaluate-harness-shift.md Step 4 + 5).
//
// `resources_discover` handler: contributes `<worktree>/.claude/skills/<name>`
// for every entry in config/pi-skills-compat.json whose status is not
// "claude-only" (that manifest is generated by scripts/pi_skills_compat.py).

// ResourcesDiscoverEvent/ResourcesDiscoverResult are not re-exported at the
// package root (only ExtensionAPI's `on("resources_discover", ...)` overload
// carries them internally) — the handler below relies on contextual typing
// from that overload instead of naming the types directly.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export type SkillCompatStatus = "loads-clean" | "needs-shim" | "claude-only";

export interface SkillCompatEntry {
  readonly name: string;
  readonly status: SkillCompatStatus;
  readonly markers: readonly string[];
  readonly notes: string;
}

export interface SkillCompatManifest {
  readonly skills: readonly SkillCompatEntry[];
}

function isSkillCompatManifest(value: unknown): value is SkillCompatManifest {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return Array.isArray(candidate.skills);
}

export function loadSkillCompatManifest(manifestPath: string): SkillCompatManifest {
  const raw = readFileSync(manifestPath, "utf-8");
  const parsed: unknown = JSON.parse(raw);
  if (!isSkillCompatManifest(parsed)) {
    throw new Error(`${manifestPath} did not parse as a skill compatibility manifest`);
  }
  return parsed;
}

/** The `.claude/skills/<name>` paths this manifest contributes — every
 * entry whose status is not "claude-only". */
export function contributedSkillPaths(
  manifest: SkillCompatManifest,
  worktreeRoot: string,
): string[] {
  return manifest.skills
    .filter((entry) => entry.status !== "claude-only")
    .map((entry) => join(worktreeRoot, ".claude", "skills", entry.name));
}

export default function gaiaSkills(pi: ExtensionAPI): void {
  pi.on("resources_discover", (_event, ctx) => {
    const manifestPath = join(ctx.cwd, "config", "pi-skills-compat.json");
    try {
      const manifest = loadSkillCompatManifest(manifestPath);
      return { skillPaths: contributedSkillPaths(manifest, ctx.cwd) };
    } catch {
      return {};
    }
  });

  pi.on("session_start", () => {
    // Pi harness parity PR 3 (plan Step 8): a durable, greppable marker the
    // no-login launch smoke (scripts/pi-launch-smoke.sh) checks for in the
    // session file to prove this extension actually loaded and ran.
    pi.appendEntry("gaia-smoke", { extension: "gaia-skills" });
  });
}
